version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/url-shortener
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
    depends_on:
      - mongo
      - redis

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80"
    depends_on:
      - app

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - client


# version: '3'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5000"  # Remove the host port mapping
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/url-shortener
#       - REDIS_URL=redis://redis:6379
#       - JWT_SECRET=your_jwt_secret
#       - GOOGLE_CLIENT_ID=your_google_client_id
#       - GOOGLE_CLIENT_SECRET=your_google_client_secret
#     depends_on:
#       - mongo
#       - redis

#   client:
#     build:
#       context: ./client
#       dockerfile: Dockerfile
#     ports:
#       - "80"  # Remove the host port mapping
#     depends_on:
#       - app

#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"

#   redis:
#     image: redis
#     ports:
#       - "6379:6379"

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - app
#       - client
